// Editorial content for district pages. SOURCE OF TRUTH: edit here, then run
//   node scripts/tracker/build-details.mjs
//
// Every record below is status "draft": written from general knowledge and NOT yet
// checked against sources. Before launch a human must verify each record, add
// `sourceUrl` + `lastVerified`, and flip status to "verified".
//
// `stays` (resorts / hotels) is intentionally absent everywhere: add it only from
// sources you may legally use (the operator's own listing, permission, official data),
// with source + lastVerified. Never copy prices/phones/photos from third-party sites.

const D = (id, summary_en, summary_bn, months, note_en, attractions, food) => ({
  id,
  status: 'draft',
  summary: { en: summary_en, bn: summary_bn },
  bestSeason: { months, note_en },
  attractions: attractions.map(([en, bn, category]) => ({ name: { en, bn }, category })),
  food: food.map(([en, bn, note]) => ({ name: { en, bn }, ...(note ? { note } : {}) })),
});

export const CONTENT = [
  D(
    'coxs-bazar',
    "Home to one of the world's longest natural sea beaches, with surf, sunsets, hill-and-sea drives and gateways to St. Martin's Island.",
    'বিশ্বের অন্যতম দীর্ঘ প্রাকৃতিক সমুদ্রসৈকতের জেলা; সূর্যাস্ত, ঢেউ আর পাহাড়-সাগরের পথ।',
    [11, 12, 1, 2, 3],
    'Dry, cooler season. Monsoon (Jun–Sep) brings rough seas.',
    [
      ["Cox's Bazar Sea Beach", 'কক্সবাজার সমুদ্রসৈকত', 'nature'],
      ['Inani Beach', 'ইনানী সৈকত', 'nature'],
      ['Himchari National Park', 'হিমছড়ি জাতীয় উদ্যান', 'nature'],
    ],
    [['Fresh seafood', 'তাজা সামুদ্রিক মাছ', 'Grilled and fried fish, prawns and crab are popular.'], ['Dried fish (shutki)', 'শুঁটকি']],
  ),
  D(
    'bandarban',
    'Bangladesh\'s hill district: mountain trails, lakes, waterfalls and indigenous communities.',
    'বাংলাদেশের পাহাড়ি জেলা: পাহাড়ি পথ, হ্রদ, ঝরনা ও আদিবাসী সংস্কৃতি।',
    [10, 11, 12, 1, 2, 3],
    'Waterfalls are fullest in the rainy season, but trails are harder then.',
    [
      ['Nilgiri', 'নীলগিরি', 'nature'],
      ['Boga Lake', 'বগা লেক', 'nature'],
      ['Nafakhum Waterfall', 'নাফাখুম ঝরনা', 'nature'],
    ],
    [['Bamboo-cooked chicken', 'বাঁশের চোঙায় রান্না মুরগি']],
  ),
  D(
    'rangamati',
    'A lake-and-hills district around Kaptai Lake, with boat rides, tribal culture and the Sajek Valley viewpoints.',
    'কাপ্তাই হ্রদ ঘিরে লেক ও পাহাড়ের জেলা; নৌভ্রমণ, উপজাতীয় সংস্কৃতি ও সাজেক উপত্যকা।',
    [10, 11, 12, 1, 2, 3],
    'Clear winter skies are best for views; monsoon mist is beautiful but roads can be difficult.',
    [
      ['Kaptai Lake', 'কাপ্তাই হ্রদ', 'nature'],
      ['Hanging Bridge (Jhulonto Bridge)', 'ঝুলন্ত সেতু', 'landmark'],
      ['Sajek Valley', 'সাজেক উপত্যকা', 'nature'],
    ],
    [['Hill-style bamboo dishes', 'পাহাড়ি বাঁশ-রান্না']],
  ),
  D(
    'sylhet',
    'Tea hills, river rapids and a major Sufi shrine; gateway to the north-east.',
    'চা-বাগান, নদী-ঝরনা আর বিখ্যাত মাজারের শহর; উত্তর-পূর্বের প্রবেশদ্বার।',
    [10, 11, 12, 1, 2, 3],
    'Ratargul is best in the rainy season when the forest floods.',
    [
      ['Ratargul Swamp Forest', 'রাতারগুল জলাবন', 'nature'],
      ['Jaflong', 'জাফলং', 'nature'],
      ['Shrine of Hazrat Shah Jalal', 'হযরত শাহজালালের মাজার', 'heritage'],
    ],
    [['Shatkora beef curry', 'শাতকরা দিয়ে গরুর মাংস', 'Cooked with the local citrus fruit shatkora.']],
  ),
  D(
    'moulvibazar',
    'The tea capital of Bangladesh, with rolling tea estates and rainforest around Sreemangal.',
    'বাংলাদেশের চায়ের রাজধানী; শ্রীমঙ্গলের চা-বাগান ও বনভূমি।',
    [10, 11, 12, 1, 2, 3],
    'Cool and dry; tea gardens are green after the monsoon.',
    [
      ['Tea gardens of Sreemangal', 'শ্রীমঙ্গলের চা-বাগান', 'nature'],
      ['Lawachara National Park', 'লাউয়াছড়া জাতীয় উদ্যান', 'nature'],
      ['Madhabkunda Waterfall', 'মাধবকুণ্ড জলপ্রপাত', 'nature'],
    ],
    [['Seven-layer tea', 'সাত রঙের চা'], ['Pineapple', 'আনারস']],
  ),
  D(
    'sunamganj',
    'A haor (wetland) district of vast seasonal lakes, bird life and boat journeys.',
    'হাওরের জেলা: বিস্তীর্ণ জলরাশি, পাখি ও নৌকাভ্রমণ।',
    [7, 8, 9, 10, 12, 1],
    'Monsoon for boat trips over the flooded haor; winter for migratory birds.',
    [
      ['Tanguar Haor', 'টাঙ্গুয়ার হাওর', 'nature'],
      ['Niladri Lake', 'নীলাদ্রি লেক', 'nature'],
      ['Jadukata River', 'যাদুকাটা নদী', 'nature'],
    ],
    [['Fresh haor fish', 'হাওরের তাজা মাছ']],
  ),
  D(
    'khulna',
    'Gateway to the Sundarbans, the world\'s largest mangrove forest, reached by boat from Khulna.',
    'বিশ্বের বৃহত্তম ম্যানগ্রোভ বন সুন্দরবনের প্রবেশদ্বার।',
    [11, 12, 1, 2, 3],
    'Winter is the most comfortable for boat tours; permits and guides are required.',
    [
      ['Sundarbans (Khulna range)', 'সুন্দরবন (খুলনা রেঞ্জ)', 'nature'],
    ],
    [['Chui jhal', 'চুইঝাল', 'A spicy dish made with chui (Piper chaba) vine, a Khulna specialty.'], ['Sundarbans honey', 'সুন্দরবনের মধু']],
  ),
  D(
    'bagerhat',
    'Home to the historic Sixty Dome Mosque (a UNESCO World Heritage Site) and a part of the Sundarbans.',
    'ইউনেস্কো বিশ্ব ঐতিহ্য ষাট গম্বুজ মসজিদ ও সুন্দরবনের অংশের জেলা।',
    [11, 12, 1, 2],
    'Cool dry weather is best for visiting heritage sites and boat trips.',
    [
      ['Sixty Dome Mosque', 'ষাট গম্বুজ মসজিদ', 'heritage'],
      ['Tomb of Khan Jahan Ali', 'খান জাহান আলীর মাজার', 'heritage'],
      ['Sundarbans (Mongla side)', 'সুন্দরবন (মোংলা)', 'nature'],
    ],
    [['Fresh river fish', 'নদীর তাজা মাছ']],
  ),
  D(
    'dhaka',
    'The capital: Mughal-era landmarks, modern architecture and the street food of Old Dhaka.',
    'রাজধানী: মুঘল আমলের স্থাপনা, আধুনিক স্থাপত্য আর পুরান ঢাকার খাবার।',
    [11, 12, 1, 2],
    'Cooler months are far more comfortable for walking tours.',
    [
      ['Lalbagh Fort', 'লালবাগ কেল্লা', 'heritage'],
      ['Ahsan Manzil', 'আহসান মঞ্জিল', 'heritage'],
      ['National Parliament House', 'জাতীয় সংসদ ভবন', 'landmark'],
    ],
    [['Old Dhaka biryani', 'পুরান ঢাকার বিরিয়ানি'], ['Bakarkhani', 'বাখরখানি']],
  ),
  D(
    'bogura',
    'Site of Mahasthangarh, among the earliest known urban archaeological sites in Bangladesh.',
    'বাংলাদেশের প্রাচীনতম নগর-প্রত্নস্থলগুলোর অন্যতম মহাস্থানগড়ের জেলা।',
    [11, 12, 1, 2, 3],
    'Dry, cool season is best for outdoor archaeological sites.',
    [
      ['Mahasthangarh', 'মহাস্থানগড়', 'heritage'],
      ['Behula-Lakhindar Basar Ghar', 'বেহুলার বাসরঘর', 'heritage'],
    ],
    [['Bogurar doi (sweet curd)', 'বগুড়ার দই']],
  ),
  D(
    'natore',
    'Known for the Natore Rajbari palace complex and the beels (wetlands) of the Chalan region.',
    'নাটোর রাজবাড়ী ও চলনবিলের জেলা।',
    [11, 12, 1, 2],
    'Cool season for palace visits; beels are fullest after the monsoon.',
    [['Natore Rajbari (Uttara Ganabhaban)', 'নাটোর রাজবাড়ী (উত্তরা গণভবন)', 'heritage']],
    [['Kachagolla', 'কাঁচাগোল্লা', 'A famous Natore sweet.']],
  ),
  D(
    'rajshahi',
    'A heritage-rich city on the Padma, known for temples, museums and mangoes.',
    'পদ্মা-তীরের ঐতিহ্যবাহী শহর; মন্দির, জাদুঘর ও আমের জন্য বিখ্যাত।',
    [11, 12, 1, 2],
    'Winter is pleasant; mango season is roughly Jun–Aug.',
    [
      ['Puthia Temple Complex', 'পুঠিয়া মন্দির কমপ্লেক্স', 'heritage'],
      ['Varendra Research Museum', 'বরেন্দ্র গবেষণা জাদুঘর', 'heritage'],
    ],
    [['Rajshahi mango', 'রাজশাহীর আম', 'Seasonal, typically in summer.']],
  ),
  D(
    'cumilla',
    'Buddhist-era ruins at Mainamati and a famous sweet shop tradition.',
    'ময়নামতির বৌদ্ধ যুগের প্রত্নস্থল ও বিখ্যাত মিষ্টির জেলা।',
    [11, 12, 1, 2, 3],
    'Dry, cooler months are best for the archaeological sites.',
    [
      ['Mainamati ruins (Shalban Vihara)', 'ময়নামতি (শালবন বিহার)', 'heritage'],
      ['Kotila Mura', 'কোটিলা মুড়া', 'heritage'],
    ],
    [['Rasmalai', 'রসমালাই', 'A well-known Cumilla sweet.']],
  ),
  D(
    'chattogram',
    "The port city between hills and sea: lakes, a city beach and WWII memorials.",
    'পাহাড় ও সাগরের মাঝের বন্দরনগরী: লেক, সমুদ্রসৈকত ও যুদ্ধ-স্মৃতিস্তম্ভ।',
    [11, 12, 1, 2, 3],
    'Cool dry months are best.',
    [
      ["Foy's Lake", 'ফয়’স লেক', 'nature'],
      ['Patenga Sea Beach', 'পতেঙ্গা সমুদ্রসৈকত', 'nature'],
      ['Chattogram War Cemetery', 'চট্টগ্রাম ওয়ার সিমেট্রি', 'heritage'],
    ],
    [['Mezban beef', 'মেজবানের গরুর মাংস', 'A traditional feast dish of Chattogram.']],
  ),
  D(
    'patuakhali',
    'Home to Kuakata, a rare beach where you can watch both sunrise and sunset over the sea.',
    'কুয়াকাটা সৈকতের জেলা, যেখান থেকে সমুদ্রের ওপর সূর্যোদয় ও সূর্যাস্ত দুটোই দেখা যায়।',
    [11, 12, 1, 2, 3],
    'Winter is calmer and drier.',
    [
      ['Kuakata Sea Beach', 'কুয়াকাটা সমুদ্রসৈকত', 'nature'],
      ['Gangamati Mangrove Forest', 'গঙ্গামতি ম্যানগ্রোভ বন', 'nature'],
    ],
    [['Fresh sea and river fish', 'সামুদ্রিক ও নদীর তাজা মাছ']],
  ),
  D(
    'gazipur',
    "A green belt north of Dhaka with national parks, a safari park and many weekend resorts.",
    'ঢাকার উত্তরে সবুজ বলয়: জাতীয় উদ্যান, সাফারি পার্ক ও উইকেন্ড রিসোর্ট।',
    [10, 11, 12, 1, 2, 3],
    'Cooler months suit outdoor park visits.',
    [
      ['Bhawal National Park', 'ভাওয়াল জাতীয় উদ্যান', 'nature'],
      ['Bangabandhu Sheikh Mujib Safari Park', 'বঙ্গবন্ধু শেখ মুজিব সাফারি পার্ক', 'nature'],
    ],
    [],
  ),
  // ---- Barishal Division ----
  D(
    'barguna',
    'A coastal district where rivers meet the Bay of Bengal, with mangrove patches and quiet beaches.',
    'নদী ও বঙ্গোপসাগরের মিলনস্থলের উপকূলীয় জেলা; ম্যানগ্রোভ বন ও নিরিবিলি সৈকত।',
    [11, 12, 1, 2],
    'Winter brings calmer water and easier boat travel.',
    [
      ['Tengragiri (Sonakata) Wildlife Sanctuary', 'টেংরাগিরি (সোনাকাটা) বন্যপ্রাণী অভয়ারণ্য', 'nature'],
      ['Bibichini Shahi Mosque', 'বিবিচিনি শাহী মসজিদ', 'heritage'],
    ],
    [['Fresh river and sea fish', 'নদী ও সাগরের তাজা মাছ']],
  ),
  D(
    'barishal',
    'Often called the "Venice of Bengal" for its rivers and canals; a hub for launch journeys from Dhaka.',
    'নদী-খালের জন্য "বাংলার ভেনিস" নামে পরিচিত; ঢাকা থেকে লঞ্চ ভ্রমণের কেন্দ্র।',
    [10, 11, 12, 1, 2],
    'After the monsoon the rivers are full but calmer.',
    [
      ['Guthia Mosque (Baitul Aman Jame Masjid)', 'গুঠিয়া মসজিদ (বায়তুল আমান জামে মসজিদ)', 'landmark'],
      ['Durga Sagar', 'দুর্গাসাগর দিঘি', 'nature'],
    ],
    [['Hilsa (ilish)', 'ইলিশ মাছ']],
  ),
  D(
    'bhola',
    "Bangladesh's largest island district, with chars, mangroves and the island of Monpura.",
    'বাংলাদেশের বৃহত্তম দ্বীপ-জেলা; চর, ম্যানগ্রোভ বন ও মনপুরা দ্বীপ।',
    [11, 12, 1, 2],
    'Winter is safest for river crossings and char visits.',
    [
      ['Monpura Island', 'মনপুরা দ্বীপ', 'nature'],
      ['Char Kukri-Mukri', 'চর কুকরি-মুকরি', 'nature'],
    ],
    [['Buffalo-milk curd (moisher doi)', 'মহিষের দই']],
  ),
  D(
    'jhalokathi',
    'A land of canals known for its seasonal floating guava markets.',
    'খাল-বিলের জেলা; মৌসুমি ভাসমান পেয়ারা বাজারের জন্য পরিচিত।',
    [7, 8, 9],
    'The floating guava market runs roughly from July to September.',
    [['Bhimruli floating guava market', 'ভিমরুলী ভাসমান পেয়ারা বাজার', 'nature']],
    [['Guava', 'পেয়ারা', 'Seasonal, mid-monsoon.']],
  ),
  D(
    'pirojpur',
    'A riverine district of canals, orchards and floating markets near Swarupkathi.',
    'খাল, বাগান আর স্বরূপকাঠির কাছে ভাসমান বাজারের নদীমাতৃক জেলা।',
    [7, 8, 9, 11, 12],
    'Floating markets peak in the monsoon; winter is pleasant for boat rides.',
    [['Atghar-Kuriana floating market', 'আটঘর-কুড়িয়ানা ভাসমান বাজার', 'nature']],
    [['Guava', 'পেয়ারা']],
  ),

  // ---- Chattogram Division ----
  D(
    'brahmanbaria',
    'A district on the Titas river with old mosques, temples and a famous sweet tradition.',
    'তিতাস নদীর তীরের জেলা; পুরোনো মসজিদ, মন্দির ও বিখ্যাত মিষ্টির ঐতিহ্য।',
    [11, 12, 1, 2],
    'Cool dry months are best for visiting heritage sites.',
    [
      ['Arifail Mosque (Sarail)', 'আরিফাইল মসজিদ (সরাইল)', 'heritage'],
      ['Kal Bhairab Temple', 'কাল ভৈরব মন্দির', 'heritage'],
    ],
    [['Chhanamukhi', 'ছানামুখী', 'A well-known Brahmanbaria sweet.']],
  ),
  D(
    'chandpur',
    'Known as the "City of Hilsa", at the meeting point of the Padma and Meghna rivers.',
    '"ইলিশের বাড়ি" নামে পরিচিত; পদ্মা ও মেঘনার মিলনস্থলে অবস্থিত।',
    [10, 11, 12, 1, 2],
    'Hilsa is most abundant in the monsoon and early autumn.',
    [['Padma–Meghna confluence (Boro Station / Molhead)', 'পদ্মা-মেঘনার মোহনা (বড় স্টেশন / মোলহেড)', 'nature']],
    [['Chandpur hilsa', 'চাঁদপুরের ইলিশ']],
  ),
  D(
    'feni',
    'A small district between Chattogram and Cumilla, with the Muhuri river project area.',
    'চট্টগ্রাম ও কুমিল্লার মাঝের ছোট জেলা; মুহুরী প্রকল্প এলাকা।',
    [11, 12, 1, 2],
    'Winter is good for birdwatching around the Muhuri project.',
    [['Muhuri Project', 'মুহুরী প্রকল্প', 'nature']],
    [],
  ),
  D(
    'khagrachhari',
    'A hill district with caves, waterfalls and the main road towards Sajek Valley.',
    'গুহা, ঝরনা আর সাজেক যাওয়ার মূল পথের পাহাড়ি জেলা।',
    [10, 11, 12, 1, 2, 3],
    'Waterfalls are strongest in the monsoon, but dry months are easier for travel.',
    [
      ['Alutila Cave', 'আলুটিলা গুহা', 'nature'],
      ['Richhang Waterfall', 'রিছাং ঝরনা', 'nature'],
      ['Debotar Pukur', 'দেবতার পুকুর', 'nature'],
    ],
    [['Hill-style bamboo dishes', 'পাহাড়ি বাঁশ-রান্না']],
  ),
  D(
    'lakshmipur',
    'A coastal district on the Meghna estuary, known for coconuts and soybeans.',
    'মেঘনা মোহনার উপকূলীয় জেলা; নারিকেল ও সয়াবিনের জন্য পরিচিত।',
    [11, 12, 1, 2],
    'Winter is calmer on the estuary.',
    [
      ['Khoa Sagar Dighi', 'খোয়া সাগর দিঘি', 'nature'],
      ['Meghna estuary at Ramgati', 'রামগতির মেঘনা মোহনা', 'nature'],
    ],
    [],
  ),
  D(
    'noakhali',
    'A coastal district whose Hatiya upazila includes Nijhum Dwip, home to spotted deer.',
    'উপকূলীয় জেলা; হাতিয়ার নিঝুম দ্বীপে চিত্রা হরিণের বাস।',
    [11, 12, 1, 2],
    'Winter is the main season for Nijhum Dwip; sea crossings are risky in the monsoon.',
    [
      ['Nijhum Dwip National Park', 'নিঝুম দ্বীপ জাতীয় উদ্যান', 'nature'],
      ['Gandhi Ashram (Jayag)', 'গান্ধী আশ্রম (জয়াগ)', 'heritage'],
    ],
    [],
  ),

  // ---- Dhaka Division ----
  D(
    'faridpur',
    'Home district of the "Rural Poet" Jasimuddin, on the banks of the Padma.',
    'পদ্মাপাড়ের জেলা; পল্লীকবি জসীমউদ্‌দীনের জন্মভূমি।',
    [11, 12, 1, 2],
    'Cool months are best for village visits.',
    [
      ["Poet Jasimuddin's house (Ambikapur)", 'পল্লীকবি জসীমউদ্‌দীনের বাড়ি (অম্বিকাপুর)', 'heritage'],
      ['Mathurapur Deul', 'মথুরাপুর দেউল', 'heritage'],
    ],
    [],
  ),
  D(
    'gopalganj',
    "Home of Tungipara and Orakandi, centre of the Matua community's pilgrimage.",
    'টুঙ্গিপাড়া ও মতুয়া সম্প্রদায়ের তীর্থস্থান ওড়াকান্দির জেলা।',
    [11, 12, 1, 2, 3],
    'Dry season is best; the Orakandi fair is held in spring.',
    [
      ['Tungipara mausoleum complex', 'টুঙ্গিপাড়া সমাধিসৌধ কমপ্লেক্স', 'heritage'],
      ['Orakandi (Harichand Thakur temple)', 'ওড়াকান্দি (হরিচাঁদ ঠাকুরের মন্দির)', 'heritage'],
    ],
    [],
  ),
  D(
    'kishoreganj',
    'Gateway to the haor wetlands, with historic sites and the Sholakia Eid ground.',
    'হাওর অঞ্চলের প্রবেশদ্বার; ঐতিহাসিক স্থান ও শোলাকিয়া ঈদগাহের জেলা।',
    [7, 8, 9, 11, 12],
    'Monsoon for the flooded haor roads; winter for heritage sites.',
    [
      ['Nikli Haor', 'নিকলী হাওর', 'nature'],
      ['Sholakia Eidgah', 'শোলাকিয়া ঈদগাহ', 'landmark'],
      ['Egarosindur Fort', 'এগারসিন্দুর দুর্গ', 'heritage'],
    ],
    [['Fresh haor fish', 'হাওরের তাজা মাছ']],
  ),
  D(
    'madaripur',
    'A river district on the Arial Khan, close to the southern end of the Padma Bridge.',
    'আড়িয়াল খাঁ নদীর তীরের জেলা; পদ্মা সেতুর দক্ষিণ প্রান্তের কাছে।',
    [11, 12, 1, 2],
    'Winter is pleasant for riverside trips.',
    [
      ['Shakuni Lake', 'শকুনি লেক', 'nature'],
      ['Arial Khan River', 'আড়িয়াল খাঁ নদী', 'nature'],
    ],
    [],
  ),
  D(
    'manikganj',
    'A short trip from Dhaka, known for grand zamindar palaces.',
    'ঢাকা থেকে অল্প দূরত্বে; জমিদারবাড়ির জন্য পরিচিত।',
    [11, 12, 1, 2],
    'Winter is ideal; Hajari date-palm molasses is a winter specialty.',
    [
      ['Baliati Zamindar Palace', 'বালিয়াটি জমিদারবাড়ি', 'heritage'],
      ['Teota Zamindar Bari', 'তেওতা জমিদারবাড়ি', 'heritage'],
    ],
    [['Hajari gur (date-palm molasses)', 'হাজারী গুড়', 'A famous winter specialty of Manikganj.']],
  ),
  D(
    'munshiganj',
    'Ancient Bikrampur: birthplace of Atish Dipankar, with a Mughal river fort and the Padma Bridge at Mawa.',
    'প্রাচীন বিক্রমপুর: অতীশ দীপঙ্করের জন্মভূমি, মুঘল জলদুর্গ ও মাওয়ার পদ্মা সেতু।',
    [11, 12, 1, 2],
    'Cool months are best for heritage visits.',
    [
      ['Idrakpur Fort', 'ইদ্রাকপুর দুর্গ', 'heritage'],
      ['Atish Dipankar memorial (Bajrayogini)', 'অতীশ দীপঙ্করের স্মৃতিস্থল (বজ্রযোগিনী)', 'heritage'],
      ['Padma Bridge (Mawa)', 'পদ্মা সেতু (মাওয়া)', 'landmark'],
    ],
    [['Fried hilsa at Mawa ghat', 'মাওয়া ঘাটের ইলিশ ভাজা']],
  ),
  D(
    'narayanganj',
    'Home of historic Sonargaon, once a capital of Bengal, and of Jamdani weaving.',
    'বাংলার প্রাচীন রাজধানী সোনারগাঁও ও জামদানি বুননের জেলা।',
    [11, 12, 1, 2],
    'Winter is best; Panam City is busy on weekends.',
    [
      ['Panam City (Sonargaon)', 'পানাম নগর (সোনারগাঁও)', 'heritage'],
      ['Folk Arts and Crafts Museum, Sonargaon', 'লোক ও কারুশিল্প জাদুঘর, সোনারগাঁও', 'heritage'],
      ['Hajiganj Fort', 'হাজীগঞ্জ দুর্গ', 'heritage'],
    ],
    [],
  ),
  D(
    'narsingdi',
    'Site of Wari-Bateshwar, one of the oldest known urban settlements in Bangladesh.',
    'উয়ারী-বটেশ্বর, বাংলাদেশের প্রাচীনতম নগর-বসতিগুলোর অন্যতম, এই জেলায়।',
    [11, 12, 1, 2],
    'Dry season is best for the archaeological site.',
    [['Wari-Bateshwar archaeological site', 'উয়ারী-বটেশ্বর প্রত্নস্থল', 'heritage']],
    [],
  ),
  D(
    'rajbari',
    'A Padma-side district around Goalanda, a historic river crossing point.',
    'গোয়ালন্দকে ঘিরে পদ্মাপাড়ের জেলা; ঐতিহাসিক নদী পারাপারের স্থান।',
    [11, 12, 1, 2],
    'Winter is calmer for river trips.',
    [['Goalanda on the Padma', 'পদ্মাপাড়ের গোয়ালন্দ', 'nature']],
    [],
  ),
  D(
    'shariatpur',
    'A Padma-side district at the southern end of the Padma Bridge.',
    'পদ্মা সেতুর দক্ষিণ প্রান্তের পদ্মাপাড়ের জেলা।',
    [11, 12, 1, 2],
    'Winter is pleasant for riverside visits.',
    [['Padma Bridge (Janjira end)', 'পদ্মা সেতু (জাজিরা প্রান্ত)', 'landmark']],
    [],
  ),
  D(
    'tangail',
    'Famous for Tangail saree weaving, zamindar palaces and the Porabari chomchom.',
    'টাঙ্গাইল শাড়ি, জমিদারবাড়ি আর পোড়াবাড়ির চমচমের জন্য বিখ্যাত।',
    [11, 12, 1, 2],
    'Winter is best for palace and weaving-village visits.',
    [
      ['Mohera Zamindar Bari', 'মহেড়া জমিদারবাড়ি', 'heritage'],
      ['Atia Mosque', 'আতিয়া মসজিদ', 'heritage'],
      ['Pathrail weaving village', 'পাথরাইল তাঁতপল্লি', 'heritage'],
    ],
    [['Porabarir chomchom', 'পোড়াবাড়ির চমচম', 'A famous Tangail sweet.']],
  ),

  // ---- Khulna Division ----
  D(
    'chuadanga',
    'A border district on the Mathabhanga river, home to the historic Carew & Co. at Darshana.',
    'মাথাভাঙ্গা নদীর তীরের সীমান্ত জেলা; দর্শনার ঐতিহাসিক কেরু অ্যান্ড কোং এখানে।',
    [11, 12, 1, 2],
    'Cool months are best.',
    [['Carew & Co. (Darshana)', 'কেরু অ্যান্ড কোং (দর্শনা)', 'landmark']],
    [],
  ),
  D(
    'jashore',
    "Birthplace of poet Michael Madhusudan Dutt and home of Bangladesh's flower-growing heartland.",
    'কবি মাইকেল মধুসূদন দত্তের জন্মভূমি ও দেশের ফুলচাষের কেন্দ্র।',
    [12, 1, 2],
    'Flower fields at Godkhali are at their best in winter.',
    [
      ['Sagardari (Michael Madhusudan Dutt birthplace)', 'সাগরদাঁড়ি (মাইকেল মধুসূদন দত্তের জন্মস্থান)', 'heritage'],
      ['Godkhali flower fields', 'গদখালীর ফুলের মাঠ', 'nature'],
    ],
    [['Jashore khejur gur (date-palm molasses)', 'যশোরের খেজুর গুড়', 'A winter specialty.']],
  ),
  D(
    'jhenaidah',
    'A district of old temples and mosques, including the Naldanga temple complex.',
    'পুরোনো মন্দির ও মসজিদের জেলা, যার মধ্যে নলডাঙ্গা মন্দির কমপ্লেক্স উল্লেখযোগ্য।',
    [11, 12, 1, 2],
    'Cool months are best for heritage visits.',
    [
      ['Naldanga temple complex', 'নলডাঙ্গা মন্দির কমপ্লেক্স', 'heritage'],
      ['Shailkupa Shahi Mosque', 'শৈলকুপা শাহী মসজিদ', 'heritage'],
    ],
    [],
  ),
  D(
    'kushtia',
    "Home of mystic poet Lalon Shah's shrine and Rabindranath Tagore's Shilaidaha Kuthibari.",
    'বাউলসম্রাট লালন শাহের মাজার ও রবীন্দ্রনাথের শিলাইদহ কুঠিবাড়ির জেলা।',
    [10, 11, 12, 1, 2, 3],
    'The Lalon festival at Cheuriya draws crowds in October and spring.',
    [
      ['Lalon Shah shrine (Cheuriya)', 'লালন শাহের মাজার (ছেঁউড়িয়া)', 'heritage'],
      ['Shilaidaha Kuthibari', 'শিলাইদহ কুঠিবাড়ি', 'heritage'],
    ],
    [['Tiler khaja', 'তিলের খাজা', 'A sesame sweet Kushtia is known for.']],
  ),
  D(
    'magura',
    'A quiet district with the ruins of Raja Sitaram Ray\'s palace at Mohammadpur.',
    'মহম্মদপুরে রাজা সীতারাম রায়ের প্রাসাদের ধ্বংসাবশেষ রয়েছে এই নিরিবিলি জেলায়।',
    [11, 12, 1, 2],
    'Cool months are best.',
    [['Raja Sitaram Ray palace ruins', 'রাজা সীতারাম রায়ের প্রাসাদ', 'heritage']],
    [],
  ),
  D(
    'meherpur',
    "Site of Mujibnagar, where Bangladesh's first government took oath in April 1971.",
    'মুজিবনগর, যেখানে ১৯৭১ সালের এপ্রিলে বাংলাদেশের প্রথম সরকার শপথ নেয়।',
    [11, 12, 1, 2, 4],
    'Commemorations are held at Mujibnagar on 17 April.',
    [
      ['Mujibnagar Memorial', 'মুজিবনগর স্মৃতিসৌধ', 'heritage'],
      ['Amjhupi Neelkuthi', 'আমঝুপি নীলকুঠি', 'heritage'],
    ],
    [],
  ),
  D(
    'narail',
    'Home of the painter S. M. Sultan, on the banks of the Chitra river.',
    'চিত্রা নদীর তীরে, শিল্পী এস. এম. সুলতানের জন্মভূমি।',
    [11, 12, 1, 2],
    'Cool months are pleasant for riverside visits.',
    [['S. M. Sultan Memorial Museum', 'এস. এম. সুলতান স্মৃতি সংগ্রহশালা', 'heritage']],
    [],
  ),
  D(
    'satkhira',
    'The western gateway to the Sundarbans via Shyamnagar, with shrimp farms along the coast.',
    'শ্যামনগর হয়ে সুন্দরবনের পশ্চিম প্রবেশদ্বার; উপকূলে চিংড়ি ঘের।',
    [11, 12, 1, 2],
    'Winter is the most comfortable for boat tours; permits are required.',
    [['Sundarbans (Satkhira range)', 'সুন্দরবন (সাতক্ষীরা রেঞ্জ)', 'nature']],
    [['Fresh shrimp and crab', 'তাজা চিংড়ি ও কাঁকড়া']],
  ),

  // ---- Mymensingh Division ----
  D(
    'jamalpur',
    'A district on the old Brahmaputra, with the Gandhi Ashram and Lauchapra hill area.',
    'পুরাতন ব্রহ্মপুত্রের তীরের জেলা; গান্ধী আশ্রম ও লাউচাপড়ার পাহাড়ি এলাকা।',
    [11, 12, 1, 2],
    'Cool months are best for the hills.',
    [
      ['Gandhi Ashram (Melandaha)', 'গান্ধী আশ্রম (মেলান্দহ)', 'heritage'],
      ['Lauchapra', 'লাউচাপড়া', 'nature'],
    ],
    [],
  ),
  D(
    'mymensingh',
    'A riverside city on the old Brahmaputra, home to Shashi Lodge and the Zainul Abedin museum.',
    'পুরাতন ব্রহ্মপুত্রের তীরের শহর; শশী লজ ও জয়নুল আবেদিন সংগ্রহশালা এখানে।',
    [11, 12, 1, 2],
    'Cool months are pleasant for walking the riverside.',
    [
      ['Shashi Lodge', 'শশী লজ', 'heritage'],
      ['Shilpacharya Zainul Abedin Museum', 'শিল্পাচার্য জয়নুল আবেদিন সংগ্রহশালা', 'heritage'],
    ],
    [['Muktagachha monda', 'মুক্তাগাছার মণ্ডা', 'A famous Mymensingh sweet.']],
  ),
  D(
    'netrokona',
    'A district of haors and the Birisiri area, with white clay hills and the Someshwari river.',
    'হাওর আর বিরিশিরি এলাকার জেলা; সাদা মাটির পাহাড় ও সোমেশ্বরী নদী।',
    [10, 11, 12, 1, 2],
    'Dry months suit Birisiri; the haor is best in the monsoon.',
    [
      ['Birisiri and Someshwari River', 'বিরিশিরি ও সোমেশ্বরী নদী', 'nature'],
      ['White clay hills (Bijoypur)', 'চিনামাটির পাহাড় (বিজয়পুর)', 'nature'],
    ],
    [['Balish mishti', 'বালিশ মিষ্টি', 'A famous Netrokona sweet.']],
  ),
  D(
    'sherpur',
    'A district at the foot of the Garo Hills, with forest picnic spots and eco parks.',
    'গারো পাহাড়ের পাদদেশের জেলা; বনের পিকনিক স্পট ও ইকো পার্ক।',
    [11, 12, 1, 2],
    'Winter is the main picnic season.',
    [
      ['Gajni Obokash', 'গজনী অবকাশ', 'nature'],
      ['Madhutila Eco Park', 'মধুটিলা ইকো পার্ক', 'nature'],
    ],
    [],
  ),

  // ---- Rajshahi Division ----
  D(
    'chapainawabganj',
    'The mango capital of Bangladesh, with Sultanate-era mosques from ancient Gaur.',
    'বাংলাদেশের আমের রাজধানী; প্রাচীন গৌড়ের সুলতানি আমলের মসজিদ।',
    [11, 12, 1, 2, 6, 7],
    'Winter for heritage sites; June–July for mango season.',
    [
      ['Choto Sona Mosque', 'ছোট সোনা মসজিদ', 'heritage'],
      ['Darasbari Mosque', 'দারাসবাড়ি মসজিদ', 'heritage'],
    ],
    [['Mango', 'আম', 'Seasonal, typically in summer.'], ['Kalai roti', 'কালাই রুটি']],
  ),
  D(
    'joypurhat',
    'A small northern district with the old Lakma Rajbari and quiet countryside.',
    'লাকমা রাজবাড়ি ও শান্ত গ্রামাঞ্চলের উত্তরের ছোট জেলা।',
    [11, 12, 1, 2],
    'Cool months are best.',
    [['Lakma Rajbari', 'লাকমা রাজবাড়ি', 'heritage']],
    [],
  ),
  D(
    'naogaon',
    'Home of Paharpur (Somapura Mahavihara), a UNESCO World Heritage Buddhist monastery.',
    'ইউনেস্কো বিশ্ব ঐতিহ্য পাহাড়পুর (সোমপুর মহাবিহার) বৌদ্ধবিহারের জেলা।',
    [11, 12, 1, 2],
    'Dry, cool months are best for the archaeological sites.',
    [
      ['Paharpur (Somapura Mahavihara)', 'পাহাড়পুর (সোমপুর মহাবিহার)', 'heritage'],
      ['Kusumba Mosque', 'কুসুম্বা মসজিদ', 'heritage'],
    ],
    [],
  ),
  D(
    'pabna',
    'A Padma-side district with the Hardinge Bridge and terracotta temples.',
    'হার্ডিঞ্জ ব্রিজ ও পোড়ামাটির মন্দিরের পদ্মাপাড়ের জেলা।',
    [11, 12, 1, 2],
    'Cool months are best.',
    [
      ['Hardinge Bridge (Paksey)', 'হার্ডিঞ্জ ব্রিজ (পাকশী)', 'landmark'],
      ['Jor Bangla Temple', 'জোড় বাংলা মন্দির', 'heritage'],
    ],
    [],
  ),
  D(
    'sirajganj',
    'A Jamuna-side district known for handloom weaving and the Jamuna Bridge.',
    'যমুনাপাড়ের জেলা; তাঁতশিল্প ও যমুনা সেতুর জন্য পরিচিত।',
    [11, 12, 1, 2],
    'Cool months are best for riverside visits.',
    [
      ['Jamuna Bridge', 'যমুনা সেতু', 'landmark'],
      ['Rabindra Kachharibari (Shahjadpur)', 'রবীন্দ্র কাছারিবাড়ি (শাহজাদপুর)', 'heritage'],
    ],
    [],
  ),

  // ---- Rangpur Division ----
  D(
    'dinajpur',
    'Home of the terracotta Kantajew Temple, Ramsagar and famous lychees.',
    'পোড়ামাটির কান্তজীউ মন্দির, রামসাগর ও বিখ্যাত লিচুর জেলা।',
    [11, 12, 1, 2, 5, 6],
    'Winter for heritage; May–June for lychee season.',
    [
      ['Kantajew Temple', 'কান্তজীউ মন্দির', 'heritage'],
      ['Ramsagar', 'রামসাগর', 'nature'],
      ['Dinajpur Rajbari', 'দিনাজপুর রাজবাড়ি', 'heritage'],
    ],
    [['Dinajpur lychee', 'দিনাজপুরের লিচু', 'Seasonal, early summer.']],
  ),
  D(
    'gaibandha',
    'A Brahmaputra-side district of river chars, known for the Rasmanjari sweet.',
    'ব্রহ্মপুত্রপাড়ের চরাঞ্চলের জেলা; রসমঞ্জরী মিষ্টির জন্য পরিচিত।',
    [11, 12, 1, 2],
    'Winter is best for char visits.',
    [['Balashi Ghat (Brahmaputra)', 'বালাসী ঘাট (ব্রহ্মপুত্র)', 'nature']],
    [['Rasmanjari', 'রসমঞ্জরী', 'A famous Gaibandha sweet.']],
  ),
  D(
    'kurigram',
    'A northern district where the Brahmaputra enters Bangladesh, with many river chars.',
    'উত্তরের জেলা, যেখানে ব্রহ্মপুত্র বাংলাদেশে প্রবেশ করেছে; অসংখ্য চর।',
    [11, 12, 1, 2],
    'Winter is best for river and char trips.',
    [['Chilmari river port', 'চিলমারী নদীবন্দর', 'nature']],
    [],
  ),
  D(
    'lalmonirhat',
    'A border district with the Teesta Barrage and the Tin Bigha Corridor.',
    'তিস্তা ব্যারেজ ও তিনবিঘা করিডরের সীমান্ত জেলা।',
    [11, 12, 1, 2],
    'Cool dry months are best.',
    [
      ['Teesta Barrage (Dalia)', 'তিস্তা ব্যারেজ (ডালিয়া)', 'landmark'],
      ['Tin Bigha Corridor', 'তিনবিঘা করিডর', 'landmark'],
    ],
    [],
  ),
  D(
    'nilphamari',
    'A northern district with Nilsagar lake and the railway town of Saidpur.',
    'নীলসাগর দিঘি ও রেলশহর সৈয়দপুরের উত্তরের জেলা।',
    [11, 12, 1, 2],
    'Winter brings migratory birds to Nilsagar.',
    [
      ['Nilsagar', 'নীলসাগর', 'nature'],
      ['Chini Mosque (Saidpur)', 'চিনি মসজিদ (সৈয়দপুর)', 'heritage'],
    ],
    [],
  ),
  D(
    'panchagarh',
    'The northernmost district, where clear winter mornings can show Kanchenjunga from Tetulia.',
    'দেশের সর্বউত্তরের জেলা; শীতের পরিষ্কার সকালে তেঁতুলিয়া থেকে কাঞ্চনজঙ্ঘা দেখা যায়।',
    [10, 11, 12],
    'Kanchenjunga is most often visible on clear mornings from October to December.',
    [
      ['Tetulia (Kanchenjunga view)', 'তেঁতুলিয়া (কাঞ্চনজঙ্ঘা দর্শন)', 'nature'],
      ['Northern tea gardens', 'উত্তরের চা-বাগান', 'nature'],
    ],
    [],
  ),
  D(
    'rangpur',
    'A divisional city with the Tajhat Palace and the Begum Rokeya memorial at Pairaband.',
    'তাজহাট জমিদারবাড়ি ও পায়রাবন্দে বেগম রোকেয়া স্মৃতিকেন্দ্রের বিভাগীয় শহর।',
    [11, 12, 1, 2],
    'Cool months are best.',
    [
      ['Tajhat Palace', 'তাজহাট জমিদারবাড়ি', 'heritage'],
      ['Begum Rokeya Memorial (Pairaband)', 'বেগম রোকেয়া স্মৃতিকেন্দ্র (পায়রাবন্দ)', 'heritage'],
    ],
    [['Haribhanga mango', 'হাড়িভাঙ্গা আম', 'Seasonal, summer.']],
  ),
  D(
    'thakurgaon',
    'A northern district with Haripur Rajbari and a giant centuries-old mango tree at Baliadangi.',
    'হরিপুর রাজবাড়ি ও বালিয়াডাঙ্গীর শত বছরের বিশাল আমগাছের উত্তরের জেলা।',
    [11, 12, 1, 2],
    'Cool months are best.',
    [
      ['Haripur Rajbari', 'হরিপুর রাজবাড়ি', 'heritage'],
      ['Giant Surjapuri mango tree (Baliadangi)', 'সূর্যাপুরী আমগাছ (বালিয়াডাঙ্গী)', 'nature'],
    ],
    [],
  ),

  // ---- Sylhet Division ----
  D(
    'habiganj',
    'Tea estates and protected forests, including Satchari National Park and Rema-Kalenga.',
    'চা-বাগান ও সংরক্ষিত বন: সাতছড়ি জাতীয় উদ্যান ও রেমা-কালেঙ্গা।',
    [10, 11, 12, 1, 2, 3],
    'Dry months are best for forest trails.',
    [
      ['Satchari National Park', 'সাতছড়ি জাতীয় উদ্যান', 'nature'],
      ['Rema-Kalenga Wildlife Sanctuary', 'রেমা-কালেঙ্গা বন্যপ্রাণী অভয়ারণ্য', 'nature'],
    ],
    [],
  ),
];
